version: 2.1

jobs:
  # print-hello:
  #   docker:
  #     - image: circleci/node:13.8.0
  #   steps:
  #     - checkout
  #     - run:
  #         command: "echo Hello"

  save_hello_world_output:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          command: "mkdir -p workspace"
          command: "echo hello wolrd > workspace/output.txt"
      - persist_to_workspace:
          root: workspce
          paths: output.txt
      
  # print_output_file:
  #   docker:
  #     - image: circleci/node:13.8.0
  #   steps:
  #     - checkout
  #     - run:
  #         command: "cat output.txt"



workflows:
  say-hello-workflow:
    jobs:
      - save_hello_world_output
