version: 2.1
commandS:
  print_pipeline_id:
    steps:
      - run: echo $CIRCLE_WORKFLOW_ID

jobs:

  reuse_command:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - print_pipeline_id

  # save_hello_world_output:
  #   docker:
  #     - image: circleci/node:13.8.0
  #   steps:
  #     - checkout
  #     - run:
  #         command: "echo hello wolrd > output.txt"
  #     - persist_to_workspace:
  #         root: .
  #         paths: output.txt
      
  # print_output_file:
  #   docker:
  #     - image: circleci/node:13.8.0
  #   steps:
  #     - checkout
  #     - attach_workspace:
  #         at: .
  #     - run:
  #         command: "cat output.txt"



workflows:
  say-hello-workflow:
    jobs:
      - reuse_command
      # - save_hello_world_output
      # - print_output_file:
      #     requires:
      #       - save_hello_world_output
