version: 2.1

jobs:
  print-hello:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"

  print-worls:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: "Say World"
          command: "echo yara success"

workflows:
  say-hello-workflow:
    jobs:
      - print-hello
      - print-world:
          require:
            - print-hello
